site_name: Robot Developer Tools for Web
repo_url: https://github.com/ranch-hand-robotics/babylon_ros
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Installation: installation.md
  - URDF Viewer: urdf.md

theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
extra:
  copy_files:
    - urdf-viewer.html
    - ros.js

use_directory_urls: false
strict: true